name: Deploy to Server

on:
  push:
    branches:
      - main  # Rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add server to known_hosts
        run: ssh-keyscan -H 172.19.18.42 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh g3@172.19.18.42 << 'EOF'
            cd /var/www/career-guidance
            git pull origin main

            # Crear red si no existe
            docker network inspect app_net >/dev/null 2>&1 || \
            docker network create --driver=bridge --subnet=192.168.101.0/24 app_net

            docker compose down
            docker compose up -d --build
          EOF
